<?php

/**
 * @file
 * Code and configuration relating to the CTA.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function gla_cta_field_widget_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\gla_core_profile\FormHelper $formHelper */
  $formHelper = \Drupal::service('gla_core_profile.form_helper');

  if ($element['#paragraph_type'] == 'cta') {
    if (!empty($element['subform']['#parents'])) {
      $cta_type_name = $formHelper->buildNameSelector($element['subform']['field_p_cta_type']);

      // Only show the image field for image CTA types.
      if (isset($element['subform']['field_p_cta_image'])) {
        $element['subform']['field_p_cta_image']['#states'] = [
          'visible' => [
            ':input[name="' . $cta_type_name . '"]' => ['value' => 'image'],
          ],
        ];
      }

      // Only show the summary field for image CTA types.
      if (isset($element['subform']['field_p_cta_summary'])) {
        $element['subform']['field_p_cta_summary']['#states'] = [
          'visible' => [
            ':input[name="' . $cta_type_name . '"]' => ['value' => 'image'],
          ],
        ];
      }
    }
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function gla_cta_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->bundle() == 'cta') {
    $cta_type = $paragraph->field_p_cta_type->value;

    if ($cta_type === 'image') {
      // Remove the wrapping div from the image field.
      $variables['content']['field_p_cta_image']['#theme'] = 'field___no_wrappers';
      $variables['content']['field_p_cta_image'][0]['#item_attributes']['class'] = [
        'u-object-cover',
        'u-w-full',
      ];
    }
  }
}
